service_names = {'AWSB2Bi': 'AWS B2B Data Interchange',
                 'AWSAmplify': 'AWS Amplify',
                 'AWSAppFabric': 'AWS AppFabric',
                 'AWSAppRunner': 'AWS App Runner',
                 'AWSAppSync': 'AWS AppSync',
                 'AWSApplicationMigrationSvc': 'AWS Application Migration Service',
                 'AWSBackup': 'AWS Backup',
                 'AWSCertificateManager': 'AWS Certificate Manager',
                 'AWSCleanRooms': 'AWS Clean Rooms',
                 'AWSCloudFormation': 'AWS CloudFormation',
                 'AWSCloudMap': 'AWS Cloud Map',
                 'AWSCloudTrail': 'AWS CloudTrail',
                 'AWSCloudWAN': 'AWS Cloud WAN',
                 'AWSCodeArtifact': 'AWS CodeArtifact',
                 'AWSCodeDeploy': 'AWS CodeDeploy',
                 'AWSCodePipeline': 'AWS CodePipeline',
                 'AWSComputeOptimizer': 'AWS Compute Optimizer',
                 'AWSConfig': 'AWS Config',
                 'AWSDataExchange': 'AWS Data Exchange',
                 'AWSDataSync': 'AWS DataSync',
                 'AWSDataTransfer': 'AWS Data Transfer',
                 'AWSDatabaseMigrationSvc': 'AWS Database Migration Service',
                 'AWSDirectConnect': 'AWS Direct Connect',
                 'AWSDirectoryService': 'AWS Directory Service',
                 'AWSELB': 'Elastic Load Balancing',
                 'AWSElasticDisasterRecovery': 'AWS Elastic Disaster Recovery',
                 'AWSElementalMediaConvert': 'AWS Elemental MediaConvert',
                 'AWSElementalMediaLive': 'AWS Elemental MediaLive',
                 'AWSElementalMediaPackage': 'AWS Elemental MediaPackage',
                 'AWSElementalMediaStore': 'AWS Elemental MediaStore',
                 'AWSElementalMediaTailor': 'AWS Elemental MediaTailor',
                 'AWSEndUserMessaging3pFees': 'AWS End User Messaging 3rd Party Fees',
                 'AWSEntityResolution': 'AWS Entity Resolution',
                 'AWSEvents': 'Amazon EventBridge',
                 'AWSFIS': 'AWS Fault Injection Simulator',
                 'AWSFMS': 'AWS Firewall Manager',
                 'AWSGlue': 'AWS Glue',
                 'AWSGlueElasticViews': 'AWS Glue Elastic Views',
                 'AWSGreengrass': 'AWS IoT Greengrass',
                 'AWSGroundStation': 'AWS Ground Station',
                 'AmazonHealthLake': 'AWS HealthLake',
                 'AWSIAMAccessAnalyzer': 'AWS IAM Access Analyzer',
                 'AWSIoT': 'AWS IoT Core',
                 'AWSIoTAnalytics': 'AWS IoT Analytics',
                 'AWSIoTEvents': 'AWS IoT Events',
                 'AWSIoTSiteWise': 'AWS IoT SiteWise',
                 'AWSIoTThingsGraph': 'AWS IoT Things Graph',
                 'AWSLakeFormation': 'AWS Lake Formation',
                 'AWSLambda': 'AWS Lambda',
                 'AWSM2': 'AWS Mainframe Modernization',
                 'AWSMDC': 'AWS Modular Data Center',
                 'AWSMediaConnect': 'AWS Elemental MediaConnect',
                 'AWSMigrationHubRefactorSpaces': 'AWS Migration Hub Refactor Spaces',
                 'AWSNetworkFirewall': 'AWS Network Firewall',
                 'AWSOutposts': 'AWS Outposts',
                 'AWSPCS': 'AWS Parallel Computing Service',
                 'AWSQueueService': 'Amazon Simple Queue Service',
                 'AWSResilienceHub': 'AWS Resilience Hub',
                 'AWSRoboMaker': 'AWS RoboMaker',
                 'AWSRTBFabric': 'AWS RTB Fabric',
                 'AWSSecretsManager': 'AWS Secrets Manager',
                 'AWSSecurityHub': 'AWS Security Hub',
                 'AWSServiceCatalog': 'AWS Service Catalog',
                 'AWSShield': 'AWS Shield',
                 'AWSStorageGateway': 'AWS Storage Gateway',
                 'AWSStorageGatewayDeepArchive': 'AWS Storage Gateway Deep Archive',
                 'AWSSupplyChain': 'AWS Supply Chain',
                 'AWSSystemsManager': 'AWS Systems Manager',
                 'AWSTransfer': 'AWS Transfer Family',
                 'AWSXRay': 'AWS X-Ray',
                 'AmazonA2I': 'Amazon Augmented AI',
                 'AmazonApiGateway': 'Amazon API Gateway',
                 'AmazonAppStream': 'Amazon AppStream 2.0',
                 'AmazonAthena': 'Amazon Athena',
                 'AmazonBedrock': 'Amazon Bedrock',
                 'AmazonBedrockFoundationModels': 'Amazon Bedrock Foundation models',
                 'AmazonBedrockService': 'Amazon Bedrock Global profile',
                 'AmazonBedrockAgentCore': 'Amazon Bedrock AgentCore',
                 'AmazonChime': 'Amazon Chime',
                 'AmazonChimeFeatures': 'Amazon Chime SDK',
                 'AmazonCloudDirectory': 'Amazon Cloud Directory',
                 'AmazonCloudFront': 'Amazon CloudFront',
                 'AmazonCloudSearch': 'Amazon CloudSearch',
                 'AmazonCloudWatch': 'Amazon CloudWatch',
                 'AmazonCognito': 'Amazon Cognito',
                 'AmazonCognitoSync': 'Amazon Cognito Sync',
                 'AmazonDAX': 'Amazon DynamoDB Accelerator (DAX)',
                 'AmazonDeadline': 'AWS Thinkbox Deadline',
                 'AmazonDetective': 'Amazon Detective',
                 'AmazonDevOpsGuru': 'Amazon DevOps Guru',
                 'AmazonDocDB': 'Amazon DocumentDB',
                 'AmazonDynamoDB': 'Amazon DynamoDB',
                 'AmazonEC2': 'Amazon Elastic Compute Cloud',
                 'AmazonECR': 'Amazon Elastic Container Registry',
                 'AmazonECS': 'Amazon Elastic Container Service',
                 'AmazonEFS': 'Amazon Elastic File System',
                 'AmazonEI': 'Amazon Elastic Inference',
                 'AmazonEKS': 'Amazon Elastic Kubernetes Service',
                 'AmazonEKSAnywhere': 'Amazon EKS Anywhere',
                 'AmazonElastiCache': 'Amazon ElastiCache',
                 'AmazonES': 'Amazon OpenSearch Service',
                 'AmazonETS': 'Amazon Elastic Transcoder',
                 'AmazonEVS': 'Amazon Elastic VMware Service',
                 'AmazonFSx': 'Amazon FSx',
                 'AmazonFinSpace': 'Amazon FinSpace',
                 'AmazonForecast': 'Amazon Forecast',
                 'AmazonFraudDetector': 'Amazon Fraud Detector',
                 'AmazonGameLift': 'Amazon GameLift',
                 'AmazonGlacier': 'Amazon S3 Glacier',
                 'AmazonGrafana': 'Amazon Managed Grafana',
                 'AmazonGuardDuty': 'Amazon GuardDuty',
                 'AmazonIVSChat': 'Amazon Interactive Video Service Chat',
                 'AmazonInspector': 'Amazon Inspector Classic',
                 'AmazonInspectorV2': 'Amazon Inspector',
                 'AmazonKendra': 'Amazon Kendra',
                 'AmazonKinesis': 'Amazon Kinesis',
                 'AmazonKinesisAnalytics': 'Amazon Kinesis Data Analytics',
                 'AmazonKinesisFirehose': 'Amazon Kinesis Data Firehose',
                 'AmazonKinesisVideo': 'Amazon Kinesis Video Streams',
                 'AmazonGameLiftStreams': 'Amazon GameLift Streams',
                 'AmazonLex': 'Amazon Lex',
                 'AmazonLightsail': 'Amazon Lightsail',
                 'AmazonLocationService': 'Amazon Location Service',
                 'AmazonLookoutEquipment': 'Amazon Lookout for Equipment',
                 'AmazonLookoutMetrics': 'Amazon Lookout for Metrics',
                 'AmazonLookoutVision': 'Amazon Lookout for Vision',
                 'AmazonMCS': 'Amazon Keyspaces',
                 'AmazonML': 'Amazon Machine Learning',
                 'AmazonMQ': 'Amazon MQ',
                 'AmazonMSK': 'Amazon Managed Streaming for Apache Kafka',
                 'AmazonMWAA': 'Amazon Managed Workflows for Apache Airflow',
                 'AmazonMacie': 'Amazon Macie',
                 'AmazonManagedBlockchain': 'Amazon Managed Blockchain',
                 'AmazonMedicalImaging': 'AWS HealthImaging',
                 'AmazonMemoryDB': 'Amazon MemoryDB',
                 'AmazonMonitron': 'AWS Monitron',
                 'AmazonNeptune': 'Amazon Neptune',
                 'AmazonOmics': 'AWS HealthOmics',
                 'AmazonPersonalize': 'Amazon Personalize',
                 'AmazonPinpoint': 'AWS End User Messaging',
                 'AmazonPolly': 'Amazon Polly',
                 'AmazonPrometheus': 'Amazon Managed Service for Prometheus',
                 'AmazonQ': 'Amazon Q',
                 'AmazonQLDB': 'Amazon Quantum Ledger Database',
                 'AmazonQuickSight': 'Amazon QuickSight',
                 'AmazonRDS': 'Amazon Relational Database Service',
                 'AmazonRedshift': 'Amazon Redshift',
                 'AmazonRekognition': 'Amazon Rekognition',
                 'AmazonRoute53': 'Amazon Route 53',
                 'AmazonS3': 'Amazon Simple Storage Service',
                 'AmazonS3GlacierDeepArchive': 'Amazon S3 Glacier Deep Archive',
                 'AmazonSES': 'Amazon Simple Email Service',
                 'AmazonSNS': 'Amazon Simple Notification Service',
                 'AmazonSWF': 'Amazon Simple Workflow Service',
                 'AmazonSageMaker': 'Amazon SageMaker',
                 'AmazonSecurityLake': 'Amazon Security Lake',
                 'AmazonSimpleDB': 'Amazon SimpleDB',
                 'AmazonStates': 'AWS Step Functions',
                 'AmazonSumerian': 'Amazon Sumerian',
                 'AmazonTextract': 'Amazon Textract',
                 'AmazonTimestream': 'Amazon Timestream',
                 'AmazonVPC': 'Amazon Virtual Private Cloud',
                 'AmazonVerifiedPermissions': 'Amazon Verified Permissions',
                 'AmazonWAM': 'Amazon WorkSpaces Application Manager',
                 'AmazonWorkDocs': 'Amazon WorkDocs',
                 'AmazonWorkLink': 'Amazon WorkLink',
                 'AmazonWorkMail': 'Amazon WorkMail',
                 'AmazonWorkSpaces': 'Amazon WorkSpaces',
                 'AmazonWorkSpacesThinClient': 'Amazon WorkSpaces Thin Client',
                 'AmazonWorkSpacesWeb': 'Amazon WorkSpaces Web',
                 'AppFlow': 'Amazon AppFlow',
                 'AuroraDSQL': 'Amazon Aurora DSQL',
                 'CloudHSM': 'AWS CloudHSM',
                 'CodeBuild': 'AWS CodeBuild',
                 'CodeCatalyst': 'Amazon CodeCatalyst',
                 'CodeGuru': 'Amazon CodeGuru',
                 'ElasticMapReduce': 'Amazon EMR',
                 'IngestionService': 'AWS Import/Export',
                 'IngestionServiceSnowball': 'AWS Snowball',
                 'IoTDeviceDefender': 'AWS IoT Device Defender',
                 'IoTDeviceManagement': 'AWS IoT Device Management',
                 'IoTTwinMaker': 'AWS IoT TwinMaker',
                 'PaymentCryptography': 'AWS Payment Cryptography',
                 'SimSpaceWeaver': 'AWS SimSpace Weaver',
                 'SnowballExtraDays': 'AWS Snowball',
                 'VMwareCloudOnAWS': 'VMware Cloud on AWS',
                 'auditmanager': 'AWS Audit Manager',
                 'awskms': 'AWS Key Management Service',
                 'awswaf': 'AWS WAF',
                 'comprehend': 'Amazon Comprehend',
                 'comprehendmedical': 'Amazon Comprehend Medical',
                 'datapipeline': 'AWS Data Pipeline',
                 'repostspace': 'AWS re:Post Private',
                 'transcribe': 'Amazon Transcribe',
                 'translate': 'Amazon Translate'}

not_expected_services = {'AmazonSumerian', 'AWSMigrationHubRefactorSpaces', 'AmazonLookoutMetrics', 'SimSpaceWeaver',
                         'AmazonPinpoint', 'AWSIoTAnalytics', 'AmazonQLDB', 'AmazonWorkLink', 'AWSRoboMaker',
                         'AWSGlueElasticViews', 'AmazonMacie', 'AmazonMonitron', 'IngestionService',
                         'AmazonLookoutEquipment', 'AmazonForecast', 'AmazonFraudDetector', 'AmazonML', 'AWSM2',
                         'AppFlow', 'AWSMDC', 'AmazonLookoutVision', 'AWSServiceCatalog', 'CodeCatalyst',
                         'AmazonCloudSearch', 'AmazonEI', 'AmazonSWF', 'datapipeline', 'AmazonWorkDocs', 'AmazonWAM',
                         'VMwareCloudOnAWS', 'AmazonTimestream', 'AmazonCognitoSync', 'AmazonSimpleDB',
                         'AmazonInspector', 'AWS Data Pipeline', 'AmazonETS', 'AWSIoTEvents', 'AmazonChime',
                         'AmazonCloudDirectory'}
